version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672" 
    restart: unless-stopped

  userapi:
    build:
      context: ./UserAPI
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - lmstudio
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - LMSTUDIO_HOST=lmstudio
    - LMSTUDIO_PORT=1234
      - ASPNETCORE_URLS=http://0.0.0.0:5168


  lmstudio:
    build:
      context: ./LMStudio
      dockerfile: Dockerfile.lmstudio


  nginx:
    image: nginx:latest
    ports:
      - "5168:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - userapi