version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  userapi:
    build:
      context: ./UserAPI
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - ASPNETCORE_URLS=http://0.0.0.0:5168
      - CONNECTION_STRING=mongodb+srv://mcculley707:Nc211266897@cluster0.o6mpa.mongodb.net/

  nginx:
    image: nginx:latest
    ports:
      - "5168:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - userapi